import { env } from "cloudflare:test";
import { describe, expect, it, vi } from "vitest";

import vector from "../../fixtures/telemetry_hmac_v1.json";
import { verifyTelemetryRequest } from "../src/broker-security";

function telemetryEnv(): Env {
  const result = Object.create(env) as Env;
  Object.defineProperty(result, "BROKER_TELEMETRY_SHARED_SECRET", {
    value: vector.shared_secret,
  });
  Object.defineProperty(result, "BROKER_TELEMETRY_ID", { value: vector.telemetry_id });
  return result;
}

describe("Python to Cloudflare telemetry HMAC conformance", () => {
  it("accepts the exact canonical vector generated by the Python client", async () => {
    vi.useFakeTimers();
    vi.setSystemTime(Number(vector.timestamp) * 1_000);
    try {
      const request = new Request(`https://control.test${vector.path}`, {
        method: vector.method,
        headers: {
          "Content-Type": "application/json",
          "X-TTWO-Telemetry-Id": vector.telemetry_id,
          "X-TTWO-Telemetry-Timestamp": vector.timestamp,
          "X-TTWO-Telemetry-Nonce": vector.nonce,
          "X-TTWO-Telemetry-Signature": vector.signature,
        },
        body: vector.body,
      });
      const verified = await verifyTelemetryRequest(request, telemetryEnv());
      expect(verified.telemetryId).toBe(vector.telemetry_id);
      expect(verified.bodyText).toBe(vector.body);
      expect(verified.payloadSha256).toBe(vector.payload_sha256);
    } finally {
      vi.useRealTimers();
    }
  });
});
