"""Read-only contracts for the future OPRA prospective-validation phase."""

from take_two_options.opra.contracts import (
    IBKR_TWS_ENVIRONMENT_VARIABLES,
    BrokerWhatIfEvidence,
    IbkrTwsProviderConfig,
    LiveChainRequest,
    LiveComboLeg,
    LiveComboMarketDataProvider,
    LiveComboQuote,
    LiveComboQuoteRequest,
    LiveOptionChainSnapshot,
    LiveOptionMarketDataProvider,
    OpraProviderConfig,
    ProviderReadinessReport,
    assess_provider_readiness,
)
from take_two_options.opra.ibkr_provider import (
    IbkrGovernanceError,
    IbkrProviderDiagnostics,
    IbkrProviderError,
    IbkrReadOnlyMarketDataProvider,
    IbkrReadPolicy,
    build_official_ibkr_provider,
    live_chain_to_market_snapshot,
)
from take_two_options.opra.shadow_campaign import (
    ShadowCampaignManifest,
    ShadowCampaignStatusReport,
    ShadowCampaignThresholds,
    evaluate_shadow_campaign,
    record_shadow_decision,
    record_shadow_realization,
)
from take_two_options.opra.validation import (
    ComboValidationLeg,
    ComboValidationPlan,
    IbkrReadOnlyValidationReport,
    IbkrValidationCheck,
    render_ibkr_validation_markdown,
    validate_ibkr_read_only,
)
from take_two_options.opra.what_if import (
    BrokerWhatIfNormalizationReport,
    BrokerWhatIfObservation,
    normalize_broker_what_if,
)

__all__ = [
    "BrokerWhatIfEvidence",
    "BrokerWhatIfNormalizationReport",
    "BrokerWhatIfObservation",
    "ComboValidationLeg",
    "ComboValidationPlan",
    "IBKR_TWS_ENVIRONMENT_VARIABLES",
    "IbkrGovernanceError",
    "IbkrProviderError",
    "IbkrProviderDiagnostics",
    "IbkrReadOnlyMarketDataProvider",
    "IbkrReadOnlyValidationReport",
    "IbkrReadPolicy",
    "IbkrTwsProviderConfig",
    "IbkrValidationCheck",
    "LiveChainRequest",
    "LiveComboLeg",
    "LiveComboMarketDataProvider",
    "LiveComboQuote",
    "LiveComboQuoteRequest",
    "LiveOptionChainSnapshot",
    "LiveOptionMarketDataProvider",
    "OpraProviderConfig",
    "ProviderReadinessReport",
    "ShadowCampaignManifest",
    "ShadowCampaignStatusReport",
    "ShadowCampaignThresholds",
    "assess_provider_readiness",
    "build_official_ibkr_provider",
    "evaluate_shadow_campaign",
    "live_chain_to_market_snapshot",
    "normalize_broker_what_if",
    "render_ibkr_validation_markdown",
    "record_shadow_decision",
    "record_shadow_realization",
    "validate_ibkr_read_only",
]
