import type { CloudPositionDossier } from "./types";

export function syntheticDemoDossier(now = new Date()): CloudPositionDossier {
  const timestamp = now.toISOString();
  const expiration = "2027-01-15T21:00:00.000Z";
  return {
    schema_version: "1.0",
    fixture_status: "SYNTHETIC_DEMO",
    dossier_id: "synthetic-ttwo-bull-call-spread-v1",
    position_id: "synthetic-ttwo-position-v1",
    created_at: timestamp,
    opened_at: timestamp,
    initial_position_state: "PAPER_OPEN",
    ticker: "TTWO",
    structure_name: "TTWO Bull Call Spread",
    structure_type: "BULL_CALL_SPREAD",
    legs: [
      {
        leg_id: "long-call-250",
        contract_identity: "TTWO  270115C00250000",
        con_id: 900001,
        local_symbol: "TTWO  270115C00250000",
        underlying: "TTWO",
        instrument_type: "option",
        side: "LONG",
        close_action: "SELL_TO_CLOSE",
        ratio: 1,
        quantity: 2,
        multiplier: 100,
        option_right: "CALL",
        strike: 250,
        expiration,
        entry_bid: 17.65,
        entry_ask: 17.75,
        entry_mid: 17.70,
        entry_executable_price: 17.75,
      },
      {
        leg_id: "short-call-300",
        contract_identity: "TTWO  270115C00300000",
        con_id: 900002,
        local_symbol: "TTWO  270115C00300000",
        underlying: "TTWO",
        instrument_type: "option",
        side: "SHORT",
        close_action: "BUY_TO_CLOSE",
        ratio: 1,
        quantity: 2,
        multiplier: 100,
        option_right: "CALL",
        strike: 300,
        expiration,
        entry_bid: 12.15,
        entry_ask: 12.25,
        entry_mid: 12.20,
        entry_executable_price: 12.15,
      },
    ],
    quantity: 2,
    multiplier: 100,
    entry_native_currency: "USD",
    policy_currency: "EUR",
    actual_entry_cash: 1023,
    actual_entry_fx: {
      rate_to_policy_currency: 0.92,
      rate_source: "SYNTHETIC_DEMO",
      rate_timestamp: timestamp,
      transaction_cost: 4,
      transaction_cost_status: "KNOWN",
      transaction_cost_source: "SYNTHETIC_DEMO",
    },
    actual_entry_commissions: 2,
    actual_entry_slippage: 3,
    initial_spot: 245,
    initial_iv: {
      "TTWO  270115C00250000": 0.40,
      "TTWO  270115C00300000": 0.38,
    },
    initial_greeks: { delta: 0.61, gamma: 0.012, theta: -0.21, vega: 0.34, rho: 0.15, vanna: 0.03, vomma: 0.08 },
    expirations: [expiration],
    managed_exit_deadline: "2026-12-18T21:00:00.000Z",
    initial_scenario_probabilities: { bear: 0.2, base: 0.5, bull: 0.3 },
    latest_promoted_model_snapshot: {
      timestamp,
      source: "SYNTHETIC_DEMO_CANONICAL_SNAPSHOT",
      status: "FIXTURE_ONLY",
      expected_remaining_pnl: 91,
      probability_profit: 0.64,
      loss_probabilities: { loss_25: 0.18, loss_50: 0.08, loss_70: 0.03 },
      var_95: 610,
      cvar_95: 720,
      assumptions: ["Synthetic demo only; not a market forecast."],
    },
    flat_spot_diagnostics: {
      timestamp,
      source: "SYNTHETIC_DEMO_CANONICAL_SNAPSHOT",
      flat_spot_7d: -18,
      flat_spot_30d: -82,
      flat_spot_60d: -176,
      flat_spot_90d: -288,
    },
    five_scores: {
      opportunity: { score_value: 68, coverage: 0.82, confidence: "DEMO", formula_version: "fixture-v1" },
      risk: { score_value: 57, coverage: 0.80, confidence: "DEMO", formula_version: "fixture-v1" },
      evidence: { score_value: 44, coverage: 0.66, confidence: "DEMO", formula_version: "fixture-v1" },
      model_agreement: { score_value: 62, coverage: 0.75, confidence: "DEMO", formula_version: "fixture-v1" },
      execution_quality: { score_value: 71, coverage: 0.88, confidence: "DEMO", formula_version: "fixture-v1" },
      source: "SYNTHETIC_DEMO",
      scope: "FIXTURE_ONLY",
      timestamp,
    },
    budget_diagnostics: { status: "SYNTHETIC_DEMO", target_budget: 1000, actual_entry_cash: 1023 },
    exit_plan: {
      status: "CONFIGURED",
      profit_target: 0.50,
      partial_profit_target: 0.45,
      operational_stop_loss: 0.30,
      exit_days_before_expiration: 21,
      iv_crush_threshold: 0.30,
      trailing_drawdown: 0.20,
      rules: [
        { rule_id: "profit_target", threshold: 0.50, suggested_action: "EXIT_REVIEW" },
        { rule_id: "operational_stop_loss", threshold: 0.30, suggested_action: "EXIT_REVIEW" },
        { rule_id: "theta_limit", threshold: 0.50, suggested_action: "WATCH" },
      ],
      human_review_required: true,
    },
    last_imported_snapshot: {
      timestamp,
      provider: "SYNTHETIC_DEMO",
      source: "FIXTURE_ONLY",
      quality: "SYNTHETIC",
      synthetic: true,
      spot: 268,
      option_quotes: [
        {
          contract_identity: "TTWO  270115C00250000",
          bid: 19.95,
          ask: 20.05,
          timestamp,
          provider: "SYNTHETIC_DEMO",
          source: "FIXTURE_ONLY",
          quality: "SYNTHETIC",
        },
        {
          contract_identity: "TTWO  270115C00300000",
          bid: 11.843478260869566,
          ask: 11.993478260869566,
          timestamp,
          provider: "SYNTHETIC_DEMO",
          source: "FIXTURE_ONLY",
          quality: "SYNTHETIC",
        },
      ],
      fx_rate_to_policy_currency: 0.92,
      fx_source: "SYNTHETIC_DEMO",
      fx_timestamp: timestamp,
      estimated_exit_commission: 2,
      estimated_exit_slippage: 3,
      estimated_exit_fx: 4,
      estimated_exit_fx_status: "ESTIMATED",
      current_iv: 0.37,
      current_greeks: { delta: 0.58, gamma: 0.010, theta: -0.19, vega: 0.29, rho: 0.14, vanna: 0.02, vomma: 0.07 },
      thesis_invalidated: false,
      data_sufficient: true,
    },
    trade_economics_ticket_hash: "a".repeat(64),
    trade_economics_schema_version: "1.2",
    git_commit: "0daf205",
    config_hash: "b".repeat(64),
    config_hash_source: "SYNTHETIC_DEMO",
    market_snapshot_hash: "c".repeat(64),
    market_snapshot_hash_source: "SYNTHETIC_DEMO",
    read_only: true,
    transmit: false,
    what_if: true,
    human_confirmation_required: true,
    order_capability: "forbidden",
  };
}
